kind: Job
apiVersion: batch/v1
metadata:
 name: esgomezm-semseg-sampling-reduce-v000
 labels:
   job-name: esgomezm-semseg-sampling-reduce-v000
spec:
 backoffLimit: 1
 template:
   metadata:
     creationTimestamp: null
   spec:
     volumes:
       - name: data
         hostPath:
           path: /srv/bcss/egomez/Semantic-Segmentation-Suite
           type: Directory
     containers:
       - name: nombre-contenedor
         image: '163.117.178.17:5000/deepcell-tf15'
         command:
           - bash
         args:
           - train_sampling_reduce_v00.sh
         workingDir: /data
         resources:
           requests:
            cpu: "4"
            memory: "14000"
           limits:
             nvidia.com/gpu: '1'
         volumeMounts:
           - name: data
             mountPath: /data
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
         imagePullPolicy: Always
     restartPolicy: OnFailure
     terminationGracePeriodSeconds: 3000
     ttlSecondsAfterFinished: 2000
     backoffLimit: 1 #13
     priorityClassName: low
